name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Updated to Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the app
        env:
          REACT_APP_ALLOWED_EMAIL: ${{ secrets.REACT_APP_ALLOWED_EMAIL }}
          REACT_APP_ALLOWED_PASSWORD: ${{ secrets.REACT_APP_ALLOWED_PASSWORD }}
        run: npm run build

      - name: Verify environment variables
        run: echo "EMAIL=${REACT_APP_ALLOWED_EMAIL}, PASSWORD=${REACT_APP_ALLOWED_PASSWORD}"
        env:
          REACT_APP_ALLOWED_EMAIL: ${{ secrets.REACT_APP_ALLOWED_EMAIL }}
          REACT_APP_ALLOWED_PASSWORD: ${{ secrets.REACT_APP_ALLOWED_PASSWORD }}

      - name: Deploy to GitHub Pages
        run: npm run deploy
